# Generated by Django 5.0.3 on 2024-03-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
